// ─────────────────────────────────────────────────────────────────────────────
// The control-plane Prisma client.
//
// Unlike `prisma` (lib/prisma.ts), this one is a plain singleton pointed at a
// single fixed schema — `platform` — because there is only ever one of it. It
// knows about all customers; nothing customer-facing may query it directly
// except through middleware/tenant.ts and routes/platform.routes.ts.
//
// Generated by `npm run platform:generate` into prisma/platform/generated.
// ─────────────────────────────────────────────────────────────────────────────

import { PrismaClient as PlatformPrismaClient } from '../../prisma/platform/generated'

export type PlatformClient = PlatformPrismaClient

/**
 * The platform schema lives in the same database as every tenant schema, so by
 * default we derive its URL from DATABASE_URL and just swap the schema. Set
 * PLATFORM_DATABASE_URL explicitly to put the control plane somewhere else.
 */
export function platformDatabaseUrl(): string {
  const explicit = process.env.PLATFORM_DATABASE_URL
  if (explicit) return explicit

  const base = process.env.DATABASE_URL
  if (!base) throw new Error('DATABASE_URL is not set — cannot derive PLATFORM_DATABASE_URL')

  const url = new URL(base)
  url.searchParams.set('schema', process.env.PLATFORM_SCHEMA || 'platform')
  // The control plane is read almost every request but writes rarely; it does
  // not need the large pool the tenant clients get.
  url.searchParams.set('connection_limit', process.env.PLATFORM_CONNECTION_LIMIT || '5')
  return url.toString()
}

const globalForPlatform = globalThis as unknown as { platformPrisma?: PlatformPrismaClient }

export const platformPrisma: PlatformPrismaClient =
  globalForPlatform.platformPrisma ??
  new PlatformPrismaClient({
    datasources: { db: { url: platformDatabaseUrl() } },
    log: ['error'],
  })

if (process.env.NODE_ENV !== 'production') globalForPlatform.platformPrisma = platformPrisma
