// ─────────────────────────────────────────────────────────────────────────────
// Starter catalog for product_sales tenants.
//
// Ten free Unsplash product photos, reused across 24 SKUs so the catalog is
// never empty on day one. Idempotent by SKU — re-running does not duplicate.
// ─────────────────────────────────────────────────────────────────────────────

import type { PrismaClient } from '@prisma/client'

const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&h=800&q=80`

/** 10 free product photos. Two or three SKUs share each one. */
const PHOTO = {
  headphones: u('photo-1505740420928-5e560c06d30e'),
  watch: u('photo-1523275335684-37898b6baf30'),
  sneakers: u('photo-1542291026-7eec264c27ff'),
  sunglasses: u('photo-1572635196237-14b3f281503f'),
  camera: u('photo-1526170375885-4d8ecf77b99f'),
  backpack: u('photo-1553062407-98eeb64c6a62'),
  chair: u('photo-1503602642458-232111445657'),
  perfume: u('photo-1541643600914-78b084683601'),
  laptop: u('photo-1496181133206-80ce9b88a853'),
  bottle: u('photo-1602143407151-7111542de6e8'),
} as const

export interface CatalogProductSeed {
  name: string
  sku: string
  category: string
  collection: string
  brand: string
  description: string
  shortDescription: string
  imageUrl: string
  unitPrice: number
  costPrice: number
  taxPercent: number
  stockQuantity: number
  minStockLevel: number
  hsnCode: string
  currency: string
  unit: string
}

export const CATALOG_PRODUCTS: CatalogProductSeed[] = [
  {
    name: 'Nova Wireless Headphones',
    sku: 'AUD-NOVA-01',
    category: 'Audio',
    collection: 'Everyday',
    brand: 'Nova',
    shortDescription: 'Over-ear Bluetooth headphones with 30-hour battery.',
    description: 'Wireless over-ear headphones with active noise isolation, foldable cups and a 30-hour battery. Comes with a 3.5 mm cable for wired fallback.',
    imageUrl: PHOTO.headphones,
    unitPrice: 4999,
    costPrice: 2800,
    taxPercent: 18,
    stockQuantity: 42,
    minStockLevel: 8,
    hsnCode: '85183000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Pulse Studio Headphones',
    sku: 'AUD-PULSE-02',
    category: 'Audio',
    collection: 'Studio',
    brand: 'Pulse',
    shortDescription: 'Wired studio headphones for mixing and calls.',
    description: 'Closed-back studio headphones with a detachable coiled cable. Tuned for monitoring, not bass boost.',
    imageUrl: PHOTO.headphones,
    unitPrice: 3499,
    costPrice: 1900,
    taxPercent: 18,
    stockQuantity: 28,
    minStockLevel: 6,
    hsnCode: '85183000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Aero Sport Earbuds',
    sku: 'AUD-AERO-03',
    category: 'Audio',
    collection: 'Sport',
    brand: 'Aero',
    shortDescription: 'Sweat-resistant earbuds with a charging case.',
    description: 'IPX4 sport earbuds with 8 hours in-ear and 24 hours from the case. Magnetic charging, three ear-tip sizes.',
    imageUrl: PHOTO.headphones,
    unitPrice: 2499,
    costPrice: 1200,
    taxPercent: 18,
    stockQuantity: 60,
    minStockLevel: 12,
    hsnCode: '85183000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Apex Classic Watch',
    sku: 'WAT-APEX-01',
    category: 'Watches',
    collection: 'Classic',
    brand: 'Apex',
    shortDescription: 'Minimal analog watch with a leather strap.',
    description: '40 mm analog watch, mineral glass, genuine leather strap. Water resistant to 3 ATM. Battery included.',
    imageUrl: PHOTO.watch,
    unitPrice: 3999,
    costPrice: 1800,
    taxPercent: 18,
    stockQuantity: 35,
    minStockLevel: 6,
    hsnCode: '91021100',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Midnight Chronograph',
    sku: 'WAT-MIDN-02',
    category: 'Watches',
    collection: 'Premium',
    brand: 'Apex',
    shortDescription: 'Black chronograph with a date window.',
    description: 'Chronograph with sub-dials, date window and a stainless-steel case. 5 ATM water resistance.',
    imageUrl: PHOTO.watch,
    unitPrice: 7499,
    costPrice: 3600,
    taxPercent: 18,
    stockQuantity: 18,
    minStockLevel: 4,
    hsnCode: '91021100',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Sprint Runner Sneakers',
    sku: 'FTW-SPR-01',
    category: 'Footwear',
    collection: 'Running',
    brand: 'Sprint',
    shortDescription: 'Lightweight running shoes with a cushioned sole.',
    description: 'Mesh upper, EVA midsole and a rubber outsole. Unisex sizing. Best for road running and daily wear.',
    imageUrl: PHOTO.sneakers,
    unitPrice: 4299,
    costPrice: 2100,
    taxPercent: 18,
    stockQuantity: 48,
    minStockLevel: 10,
    hsnCode: '64041190',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Street High-Top',
    sku: 'FTW-STR-02',
    category: 'Footwear',
    collection: 'Street',
    brand: 'Sprint',
    shortDescription: 'Canvas high-tops for everyday wear.',
    description: 'High-top canvas sneakers with a padded collar and gum sole. Available in standard UK sizes.',
    imageUrl: PHOTO.sneakers,
    unitPrice: 2999,
    costPrice: 1400,
    taxPercent: 18,
    stockQuantity: 40,
    minStockLevel: 8,
    hsnCode: '64041990',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Trail Walking Shoe',
    sku: 'FTW-TRL-03',
    category: 'Footwear',
    collection: 'Outdoor',
    brand: 'Trail',
    shortDescription: 'Grip-sole walking shoe for light trails.',
    description: 'Low-cut walking shoe with a lugged outsole and water-resistant upper. For parks and light trails, not mountaineering.',
    imageUrl: PHOTO.sneakers,
    unitPrice: 4599,
    costPrice: 2300,
    taxPercent: 18,
    stockQuantity: 22,
    minStockLevel: 5,
    hsnCode: '64041190',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Coast Polarized Sunglasses',
    sku: 'EYE-CST-01',
    category: 'Eyewear',
    collection: 'Outdoor',
    brand: 'Coast',
    shortDescription: 'Polarized UV400 sunglasses with a metal frame.',
    description: 'Polarized lenses, UV400 protection, lightweight metal frame and a hard case. Unisex.',
    imageUrl: PHOTO.sunglasses,
    unitPrice: 1899,
    costPrice: 700,
    taxPercent: 18,
    stockQuantity: 55,
    minStockLevel: 10,
    hsnCode: '90041000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Urban Round Shades',
    sku: 'EYE-URB-02',
    category: 'Eyewear',
    collection: 'Everyday',
    brand: 'Coast',
    shortDescription: 'Round acetate sunglasses for daily wear.',
    description: 'Acetate round frame with grey tinted lenses. Includes a microfibre pouch.',
    imageUrl: PHOTO.sunglasses,
    unitPrice: 1499,
    costPrice: 550,
    taxPercent: 18,
    stockQuantity: 50,
    minStockLevel: 10,
    hsnCode: '90041000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Snap Instant Camera',
    sku: 'CAM-SNP-01',
    category: 'Cameras',
    collection: 'Fun',
    brand: 'Snap',
    shortDescription: 'Instant-print camera for parties and gifts.',
    description: 'Instant camera that prints credit-card sized photos. Uses standard instant film packs sold separately.',
    imageUrl: PHOTO.camera,
    unitPrice: 5999,
    costPrice: 3200,
    taxPercent: 18,
    stockQuantity: 16,
    minStockLevel: 4,
    hsnCode: '90064000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Vista Compact Camera',
    sku: 'CAM-VST-02',
    category: 'Cameras',
    collection: 'Travel',
    brand: 'Vista',
    shortDescription: 'Pocket compact camera with a zoom lens.',
    description: 'Point-and-shoot compact with 10x zoom, HD video and a rechargeable battery. SD card not included.',
    imageUrl: PHOTO.camera,
    unitPrice: 8999,
    costPrice: 5100,
    taxPercent: 18,
    stockQuantity: 12,
    minStockLevel: 3,
    hsnCode: '85258900',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Trail Daypack 20L',
    sku: 'BAG-TRL-01',
    category: 'Bags',
    collection: 'Outdoor',
    brand: 'Trail',
    shortDescription: '20 litre daypack with a laptop sleeve.',
    description: 'Water-resistant 20L pack, padded laptop sleeve up to 15", chest strap and bottle pockets.',
    imageUrl: PHOTO.backpack,
    unitPrice: 2199,
    costPrice: 950,
    taxPercent: 18,
    stockQuantity: 38,
    minStockLevel: 8,
    hsnCode: '42029200',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Metro Laptop Backpack',
    sku: 'BAG-MTR-02',
    category: 'Bags',
    collection: 'Work',
    brand: 'Metro',
    shortDescription: 'Office backpack with organiser pockets.',
    description: 'Slim office backpack, 16" laptop sleeve, organiser panel and a luggage-pass-through strap.',
    imageUrl: PHOTO.backpack,
    unitPrice: 2799,
    costPrice: 1250,
    taxPercent: 18,
    stockQuantity: 30,
    minStockLevel: 6,
    hsnCode: '42029200',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Lumen Accent Stool',
    sku: 'HOM-LMN-01',
    category: 'Home',
    collection: 'Living',
    brand: 'Lumen',
    shortDescription: 'Solid wood accent stool for living rooms.',
    description: 'Round solid-wood stool, 45 cm high. Use as extra seating or a side table. Flat-packed, hardware included.',
    imageUrl: PHOTO.chair,
    unitPrice: 3299,
    costPrice: 1600,
    taxPercent: 18,
    stockQuantity: 20,
    minStockLevel: 4,
    hsnCode: '94016900',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Oak Side Table',
    sku: 'HOM-OAK-02',
    category: 'Home',
    collection: 'Living',
    brand: 'Lumen',
    shortDescription: 'Small oak-finish side table.',
    description: 'Compact side table with an oak finish and a lower shelf. Fits next to a sofa or bed.',
    imageUrl: PHOTO.chair,
    unitPrice: 4499,
    costPrice: 2200,
    taxPercent: 18,
    stockQuantity: 14,
    minStockLevel: 3,
    hsnCode: '94036000',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Noir Eau de Parfum 50ml',
    sku: 'FRG-NOR-01',
    category: 'Fragrance',
    collection: 'Premium',
    brand: 'Noir',
    shortDescription: 'Woody unisex eau de parfum, 50 ml.',
    description: 'Woody-spicy eau de parfum. Lasts 6–8 hours. 50 ml spray bottle in a gift box.',
    imageUrl: PHOTO.perfume,
    unitPrice: 2499,
    costPrice: 900,
    taxPercent: 18,
    stockQuantity: 44,
    minStockLevel: 8,
    hsnCode: '33030090',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Bloom Day Perfume 30ml',
    sku: 'FRG-BLM-02',
    category: 'Fragrance',
    collection: 'Everyday',
    brand: 'Bloom',
    shortDescription: 'Light floral day perfume, 30 ml.',
    description: 'Fresh floral scent for daytime. 30 ml travel-friendly bottle.',
    imageUrl: PHOTO.perfume,
    unitPrice: 1299,
    costPrice: 450,
    taxPercent: 18,
    stockQuantity: 52,
    minStockLevel: 10,
    hsnCode: '33030090',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'WorkBook 14 Laptop',
    sku: 'CMP-WBK-01',
    category: 'Computing',
    collection: 'Work',
    brand: 'WorkBook',
    shortDescription: '14-inch laptop for office and study.',
    description: '14" FHD, 8 GB RAM, 256 GB SSD, Windows. HDMI, USB-C and a full-size keyboard. 1 year onsite warranty.',
    imageUrl: PHOTO.laptop,
    unitPrice: 42990,
    costPrice: 34000,
    taxPercent: 18,
    stockQuantity: 10,
    minStockLevel: 3,
    hsnCode: '84713010',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'SlimBook Air 13',
    sku: 'CMP-SLM-02',
    category: 'Computing',
    collection: 'Premium',
    brand: 'SlimBook',
    shortDescription: 'Thin 13-inch laptop under 1.2 kg.',
    description: '13" laptop, 16 GB RAM, 512 GB SSD. Fanless chassis, all-day battery. USB-C charger included.',
    imageUrl: PHOTO.laptop,
    unitPrice: 68990,
    costPrice: 54000,
    taxPercent: 18,
    stockQuantity: 6,
    minStockLevel: 2,
    hsnCode: '84713010',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Office Dock Laptop 15',
    sku: 'CMP-OFC-03',
    category: 'Computing',
    collection: 'Work',
    brand: 'WorkBook',
    shortDescription: '15-inch laptop with a numeric keypad.',
    description: '15.6" FHD, 16 GB RAM, 512 GB SSD, numeric keypad. Built for spreadsheets and long desk sessions.',
    imageUrl: PHOTO.laptop,
    unitPrice: 52990,
    costPrice: 41000,
    taxPercent: 18,
    stockQuantity: 8,
    minStockLevel: 2,
    hsnCode: '84713010',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Hydro Steel Bottle 750ml',
    sku: 'KIT-HYD-01',
    category: 'Drinkware',
    collection: 'Everyday',
    brand: 'Hydro',
    shortDescription: 'Insulated steel bottle, 750 ml.',
    description: 'Double-wall stainless steel. Keeps drinks cold ~18 hours, hot ~8 hours. Leak-proof lid.',
    imageUrl: PHOTO.bottle,
    unitPrice: 899,
    costPrice: 320,
    taxPercent: 18,
    stockQuantity: 80,
    minStockLevel: 15,
    hsnCode: '96170012',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Daily Sip Bottle 500ml',
    sku: 'KIT-SIP-02',
    category: 'Drinkware',
    collection: 'Everyday',
    brand: 'Hydro',
    shortDescription: 'Compact 500 ml steel bottle.',
    description: 'Smaller 500 ml insulated bottle that fits cup holders and bags. Same steel build as the 750 ml.',
    imageUrl: PHOTO.bottle,
    unitPrice: 699,
    costPrice: 240,
    taxPercent: 18,
    stockQuantity: 90,
    minStockLevel: 15,
    hsnCode: '96170012',
    currency: 'INR',
    unit: 'pcs',
  },
  {
    name: 'Sport Flask 1L',
    sku: 'KIT-SPT-03',
    category: 'Drinkware',
    collection: 'Sport',
    brand: 'Trail',
    shortDescription: '1 litre sport flask with a straw lid.',
    description: 'Wide-mouth 1L flask with a straw lid for gym and travel. BPA-free inner, carry loop.',
    imageUrl: PHOTO.bottle,
    unitPrice: 1099,
    costPrice: 400,
    taxPercent: 18,
    stockQuantity: 36,
    minStockLevel: 8,
    hsnCode: '96170012',
    currency: 'INR',
    unit: 'pcs',
  },
]

export async function seedProductCatalog(db: PrismaClient): Promise<{ created: number; skipped: number }> {
  let created = 0
  let skipped = 0
  for (const p of CATALOG_PRODUCTS) {
    const existing = await db.product.findUnique({ where: { sku: p.sku }, select: { id: true } })
    if (existing) {
      skipped++
      continue
    }
    await db.product.create({
      data: {
        name: p.name,
        sku: p.sku,
        category: p.category,
        collection: p.collection,
        brand: p.brand,
        description: p.description,
        shortDescription: p.shortDescription,
        imageUrl: p.imageUrl,
        unitPrice: p.unitPrice,
        costPrice: p.costPrice,
        minSellingPrice: Math.round(p.unitPrice * 0.9),
        taxPercent: p.taxPercent,
        stockQuantity: p.stockQuantity,
        minStockLevel: p.minStockLevel,
        hsnCode: p.hsnCode,
        currency: p.currency,
        unit: p.unit,
        active: true,
      },
    })
    created++
  }
  return { created, skipped }
}
