import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { dashboardApi, type SuperAdminOverview } from '@/lib/api'
import { useAuthStore } from '@/stores/auth.store'
import { AlertTriangle, Building2, Database, FolderCog, ShieldCheck, UserCog, Users } from 'lucide-react'

type Icon = typeof Users
function Metric({ label, value, icon: IconComponent, tone }: { label: string; value: number; icon: Icon; tone: string }) {
  return <div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString()}</p></div><div className={`rounded-xl p-3 ${tone}`}><IconComponent className="h-5 w-5" /></div></div></div>
}
function AdminLink({ to, title, subtitle, icon: IconComponent }: { to: '/app/users' | '/app/branches' | '/app/lead-config' | '/app/settings' | '/app/reports' | '/app/products'; title: string; subtitle: string; icon: Icon }) {
  return <Link to={to} className="rounded-xl border p-4 transition hover:border-primary/40 hover:bg-primary/5"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary/10 p-2 text-primary"><IconComponent className="h-4 w-4" /></div><div><p className="text-sm font-bold">{title}</p><p className="text-xs text-muted-foreground">{subtitle}</p></div></div></Link>
}
export function SuperAdminDashboard() {
  const user = useAuthStore((state) => state.user)
  const { data, isLoading, isError } = useQuery<SuperAdminOverview>({ queryKey: ['super-admin-overview'], queryFn: dashboardApi.superAdmin, staleTime: 60_000 })
  const metrics = data?.metrics
  return <div className="space-y-7 animate-in fade-in duration-500">
    <section className="rounded-2xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white shadow-xl md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-sm font-bold text-indigo-200"><ShieldCheck className="h-4 w-4" />SUPER ADMIN CONSOLE</div><h1 className="text-3xl font-black">Welcome, {user?.name?.split(' ')[0] || 'Admin'}</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Organization-wide control center for people, branches, lead operations, and system configuration.</p></div><Link to="/app/leads/new" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-indigo-50">Add lead</Link></div></section>
    {isError && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">Unable to load the super-admin overview. Please refresh or check your session.</div>}
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active team" value={metrics?.activeUsers || 0} icon={Users} tone="bg-blue-100 text-blue-700" /><Metric label="Active branches" value={metrics?.activeBranches || 0} icon={Building2} tone="bg-violet-100 text-violet-700" /><Metric label="Live leads" value={metrics?.totalLeads || 0} icon={Database} tone="bg-emerald-100 text-emerald-700" /><Metric label="Overdue follow-ups" value={metrics?.overdueFollowups || 0} icon={AlertTriangle} tone="bg-amber-100 text-amber-700" /></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="xl:col-span-2 rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Control center</h2><p className="text-sm text-muted-foreground">Direct access to privileged administration.</p></div><FolderCog className="h-5 w-5 text-primary" /></div><div className="grid gap-3 sm:grid-cols-2"><AdminLink to="/app/users" title="Team members" subtitle={`${metrics?.activeUsers || 0} active of ${metrics?.totalUsers || 0}`} icon={UserCog} /><AdminLink to="/app/branches" title="Branches" subtitle={`${metrics?.activeBranches || 0} active of ${metrics?.totalBranches || 0}`} icon={Building2} /><AdminLink to="/app/lead-config" title="Lead workflow" subtitle="Statuses, departments and routing" icon={Database} /><AdminLink to="/app/settings" title="System settings" subtitle="Global application configuration" icon={FolderCog} /><AdminLink to="/app/reports" title="Performance reports" subtitle={`${metrics?.todayLeads || 0} new leads today`} icon={Database} /><AdminLink to="/app/products" title="Catalog" subtitle="Products and stock" icon={Database} /></div></div><div className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-black">Active team by role</h2><div className="mt-4 space-y-3">{(data?.staffByRole || []).slice(0, 7).map((role) => <div key={role.role} className="flex items-center justify-between"><span className="capitalize text-sm text-muted-foreground">{role.role.replace('-', ' ')}</span><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-black">{role.count}</span></div>)}{!isLoading && !data?.staffByRole.length && <p className="text-sm text-muted-foreground">No active staff found.</p>}</div></div></section>
    <section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-black">Branch coverage</h2><div className="mt-4 divide-y">{(data?.branches || []).map((branch) => <div key={branch.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-bold">{branch.name}</p><p className="text-xs text-muted-foreground">{branch.city || 'Location not set'}</p></div><span className="text-sm font-black">{branch.activeUsers} <span className="text-xs font-medium text-muted-foreground">team</span></span></div>)}{!isLoading && !data?.branches.length && <p className="py-3 text-sm text-muted-foreground">No active branches found.</p>}</div></div><div className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-black">Recent sign-ins</h2><div className="mt-4 divide-y">{(data?.recentLogins || []).map((login, index) => <div key={`${login.user.id}-${login.at}-${index}`} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-bold">{login.user.name}</p><p className="text-xs text-muted-foreground capitalize">{login.user.role}{login.user.branch ? ` · ${login.user.branch}` : ''}</p></div><time className="shrink-0 text-xs text-muted-foreground">{new Date(login.at).toLocaleString()}</time></div>)}{!isLoading && !data?.recentLogins.length && <p className="py-3 text-sm text-muted-foreground">No sign-ins in the last 7 days.</p>}</div></div></section>
  </div>
}